### ISSUE TITLE
反向传播不能回传，一直看到这个说法，我想您有了通俗易懂的解释，求讲解这种情形，多谢

### ISSUE THREAD

**Issue by guotong1988** [lan2720/GAN-AEL#2]
具体什么样的神经网络，会产生 反向传播不能回传 的情形？
一直看论文里说到这个，却一直没有直观认识。
多谢@lan2720

**Comment by lan2720** [comment]
@guotong1988 The question is not related to the project itself, so i will close this issue. You could search the answer in other ways.

**Comment by guotong1988** [comment]
大神如果知道就顺便解答一下呗，多谢！
